/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Md.Imran Hossain
 */
public class search extends javax.swing.JFrame {
Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Signin
     */
    int x,

    /**
     * Creates new form Signin
     */
    y;
    
    public search() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void showTableData(){
try{
con = DriverManager.getConnection("jdbc:mysql://localhost/jobsearch","root","");
String sql = "SELECT * FROM post";
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
 
}
 
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new cambodia.raven.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jobcategoryTextField = new javax.swing.JTextField();
        jobtitleTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aboutjobTextArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        experienceTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        salaryTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        companyTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        QualificationTextArea = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        dateChooser1.setTextRefernce(locationTextField);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 120, 215));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 102, 153));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/undo_26px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 875, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        jPanel2.setBackground(new java.awt.Color(19, 34, 65));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 70, 490));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Job category");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, 30));

        jobcategoryTextField.setBackground(new java.awt.Color(19, 34, 65));
        jobcategoryTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jobcategoryTextField.setForeground(new java.awt.Color(255, 255, 255));
        jobcategoryTextField.setToolTipText("Search");
        jobcategoryTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jobcategoryTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jobcategoryTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(jobcategoryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 201, 34));

        jobtitleTextField.setBackground(new java.awt.Color(19, 34, 65));
        jobtitleTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jobtitleTextField.setForeground(new java.awt.Color(255, 255, 255));
        jobtitleTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.add(jobtitleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 201, 34));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Job title");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Company");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, -1, 30));

        locationTextField.setBackground(new java.awt.Color(19, 34, 65));
        locationTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locationTextField.setForeground(new java.awt.Color(255, 255, 255));
        locationTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.add(locationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 660, 200, 34));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Location");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, -1, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("About job");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 770, 70, 120));

        aboutjobTextArea.setBackground(new java.awt.Color(19, 34, 65));
        aboutjobTextArea.setColumns(20);
        aboutjobTextArea.setForeground(new java.awt.Color(255, 255, 255));
        aboutjobTextArea.setRows(5);
        jScrollPane2.setViewportView(aboutjobTextArea);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 770, 540, 120));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Experience");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 720, -1, 30));

        experienceTextField.setBackground(new java.awt.Color(19, 34, 65));
        experienceTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        experienceTextField.setForeground(new java.awt.Color(255, 255, 255));
        experienceTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.add(experienceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, 201, 34));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Salary");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, -1, 30));

        salaryTextField.setBackground(new java.awt.Color(19, 34, 65));
        salaryTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salaryTextField.setForeground(new java.awt.Color(255, 255, 255));
        salaryTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.add(salaryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 201, 34));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Email");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, -1, 30));

        emailTextField.setBackground(new java.awt.Color(19, 34, 65));
        emailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 660, 201, 34));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Select Category");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 30));

        categoryComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accounts & Finance", "Bank / Insurance / Leasing", "Garment's / Textile", "Electrical / Construction", "Agriculture / Fisheries", "Driving / Motor technology", "Architecture's / Civil Engineer's", "Call Center / Customer Care", "It & Telecommunication", "Sales and Marketing", "Travel / Tourism / Hotel", "Other's" }));
        jPanel3.add(categoryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 201, 34));

        jToggleButton1.setText("Search");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 30));

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Job_Title", "Company", "Location", "About_Job", "Qualification", "Experience", "Salary", "E-Mail", "Phone"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 880, 220));

        companyTextField.setBackground(new java.awt.Color(19, 34, 65));
        companyTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        companyTextField.setForeground(new java.awt.Color(255, 255, 255));
        companyTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.add(companyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 200, 34));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Qualification");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, -1, 22));

        QualificationTextArea.setBackground(new java.awt.Color(19, 34, 65));
        QualificationTextArea.setColumns(20);
        QualificationTextArea.setForeground(new java.awt.Color(255, 255, 255));
        QualificationTextArea.setRows(5);
        jScrollPane4.setViewportView(QualificationTextArea);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 201, 80));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Phone");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 710, -1, 30));

        phoneTextField.setBackground(new java.awt.Color(19, 34, 65));
        phoneTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneTextField.setForeground(new java.awt.Color(255, 255, 255));
        phoneTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 710, 201, 34));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("ID");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 30, 30));

        idTextField.setBackground(new java.awt.Color(19, 34, 65));
        idTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idTextField.setForeground(new java.awt.Color(255, 255, 255));
        idTextField.setToolTipText("Search");
        idTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        idTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 201, 34));

        jToggleButton2.setText("Search");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 70, 30));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 870, 300, 80));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("------------------------------------------------------  For details search by Id here         -----------------------------------------------------");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 890, -1));
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 80, 40));
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 930, 280, 90));

        jScrollPane1.setViewportView(jPanel3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 920, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       int xx = evt.getXOnScreen();
       int yy = evt.getYOnScreen();
       this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
new candidate().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
try{
con = DriverManager.getConnection("jdbc:mysql://localhost/jobsearch1","root","");
String sql = "SELECT `ID`, `Job_Title`, `Company`, `Location`, `About_job`, `Qualification`, `Experience`, `Salary`, `E-mail`, `Phone` FROM `post` WHERE Job_Category=?";
pst = con.prepareStatement(sql);
pst.setString(1, categoryComboBox.getSelectedItem().toString());
rs=pst.executeQuery();
jTable1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
 
}        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
try{
con = DriverManager.getConnection("jdbc:mysql://localhost/jobsearch1","root","");
String sql = "SELECT * FROM post WHERE ID=?";
pst = con.prepareStatement(sql);
pst.setString(1, idTextField.getText());
rs=pst.executeQuery();
if(rs.next()){
String add1 = rs.getString("Job_Title");
jobtitleTextField.setText(add1);
String add2 = rs.getString("Company");
companyTextField.setText(add2);
String add3 = rs.getString("About_Job");
aboutjobTextArea.setText(add3);
String add4 = rs.getString("Location");
locationTextField.setText(add4);
String add5 = rs.getString("Qualification");
QualificationTextArea.setText(add5);
String add6 = rs.getString("Experience");
experienceTextField.setText(add6);
String add7 = rs.getString("Salary");
salaryTextField.setText(add7);
String add8 = rs.getString("E-Mail");
emailTextField.setText(add8);
String add9 = rs.getString("Phone");
phoneTextField.setText(add9);
String add10 = rs.getString("About_Job");
aboutjobTextArea.setText(add10);
String add11 = rs.getString("Job_Category");
jobcategoryTextField.setText(add11);
}
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
 
}        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        this.setState(Home.ICONIFIED);
    }//GEN-LAST:event_jLabel6MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea QualificationTextArea;
    private javax.swing.JTextArea aboutjobTextArea;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JTextField companyTextField;
    private cambodia.raven.DateChooser dateChooser1;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField experienceTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField jobcategoryTextField;
    private javax.swing.JTextField jobtitleTextField;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField salaryTextField;
    // End of variables declaration//GEN-END:variables
}
